name: Build Windows EXE

on: [push]  # Runs on every git push

jobs:
  build:
    runs-on: windows-latest  # Windows runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Match your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas numpy matplotlib openpyxl  # Add other deps here

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed several_inputs_main_2.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-EXE
          path: dist/your_script.exe  # Path to the generated EXE
